# Generated by Django 4.2.28 on 2026-02-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_covers/'),
        ),
    ]
