# Generated by Django 4.2.28 on 2026-03-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_userprofile_date_of_birth_userprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='join_password',
            field=models.CharField(blank=True, help_text='Optional password required to join this group. Leave blank for open access.', max_length=128, null=True),
        ),
    ]
