# Generated by Django 4.2.28 on 2026-03-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_studygroup_join_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='max_members',
            field=models.IntegerField(default=0, help_text='0 means unlimited'),
        ),
    ]
